repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML>=6.0.12.12
        args: [--config-file=mypy.ini]
