# This is a temporary config with all checks disabled
repos:
  - repo: local
    hooks:
      - id: placeholder
        name: placeholder
        entry: echo
        language: system
        always_run: false
