rules:
  # Code Style
  max_line_length: 100
  max_file_lines: 300
  require_type_hints: true
  ignore_patterns:
    - "**/test_*.py"
    - "**/conftest.py"
    - "**/tests/*.py"

  # Documentation
  required_docstrings: true
  min_docstring_words: 5

  # Complexity
  complexity:
    max_nested_blocks: 3
    max_cognitive_complexity: 15

  # Functions
  functions:
    max_arguments: 5
    max_default_args: 3
    max_function_lines: 50
    require_return_type: true
    warn_unused: true

  # Magic Numbers
  magic_numbers:
    enabled: true
    ignore_values: [0, 1, -1, 100]
    require_constants: true
    ignore_in_tests: true

  # Imports
  imports:
    groups: ["stdlib", "third_party", "local"]
    require_sorted: true
    require_separate_groups: true
    warn_on_relative_imports: true

  # Naming
  naming_conventions:
    classes: "PascalCase"
    functions: "snake_case"
    variables: "snake_case"
    constants: "UPPER_CASE"
    type_hints: "ignore"

  # Testing
  testing:
    min_assertions: 1
    require_docstrings: true
    ignore_unused: true

  # Code Duplication
  duplication:
    min_lines: 6
    similarity_threshold: 0.85
    ignore_docstrings: true
    ignore_comments: true

  # Test File Rules
  test_files:
    patterns:
      - "**/test_*.py"
      - "**/tests/*.py"
      - "**/conftest.py"
    ignore_rules:
      - unused_code
      - magic_numbers
      - docstring_length
    min_test_coverage: 80
    require_assertions: true
    require_mocks: false
    max_test_size: 500

  # Performance Rules
  performance:
    max_loop_depth: 2
    max_function_calls: 3
    prefer_list_comprehension: true
    warn_inefficient_operations: true
    cache_expensive_calls: true

  # Security Rules
  security:
    check_sql_injection: true
    check_xss: true
    check_file_access: true
    disallow_eval: true
    require_input_validation: true
    check_permissions: true

  # Documentation Rules
  documentation:
    require_module_docstring: true
    require_class_docstring: true
    require_function_docstring: true
    min_docstring_length: 10
    check_parameter_docs: true
    check_return_docs: true
    check_raises_docs: true
