rules:
  # Code Style
  max_line_length: 100
  max_file_lines: 300
  require_type_hints: true
  spacing:
    around_operators: true
    after_comma: true
    around_assignments: true

  # Documentation
  required_docstrings: true
  min_docstring_words: 5

  # Complexity
  complexity:
    max_nested_blocks: 3
    max_cognitive_complexity: 15

  # Functions
  functions:
    max_arguments: 5
    max_default_args: 3
    max_function_lines: 50
    require_return_type: true
    warn_unused: true

  # Magic Numbers
  magic_numbers:
    enabled: true
    ignore_values: [0, 1, -1]
    require_constants: true

  # Imports
  imports:
    groups: ["stdlib", "third_party", "local"]
    require_sorted: true
    require_separate_groups: true
    warn_on_relative_imports: true

  # Naming
  naming_conventions:
    classes: "PascalCase"
    functions: "snake_case"
    variables: "snake_case"
    constants: "UPPER_CASE"

  # Testing
  testing:
    min_assertions: 1
    require_docstrings: true
