name: Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.py" # Only trigger on Python file changes

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Needed to post review comments
      contents: read # Needed to checkout code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python -m src.reviewer
