name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: |
          pytest tests/ -v --cov=src/ --cov-report=xml

      - name: Run AI Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_TOKEN: ${{ secrets.ANTHROPIC_API_KEY }}
          AI_PROVIDER: "anthropic"
          AI_MODEL: "claude-3-sonnet-20240229"
        run: |
          python src/cli/review_pr.py ${{ github.repository }} ${{ github.event.pull_request.number }}
